### PR TITLE
Implemented random choice on partial filename match

### PR DESCRIPTION
**Pull request by flapjax**
### I am submitting a...
```
 [ ] Bug fix
 [X] Feature addition or improvement for an existing cog
```

### Name of the cog in question:
playsound.py

### Description of my bug fix/improvement:
Implemented the ability to select and play a random sound based on partial filename match, when no exact match is found.

-Exact matches with 'soundname' still take priority.
-Exact matches with 'soundname', still result in error when multiple file extensions exist
-If no exact match is found, but one or more filenames **start** with 'soundname', one of those sounds is
selected at random and played. (identical file names with multiple extensions are allowed in this case)

For example, given the following sound files:
trumpet_high.mp3
trumpet_med.mp3
trumpet_low.mp3
trumpet_low.wav

[p]playsound trumpet_high    (plays trumpet_high.mp3)  -- same as existing
[p]playsound trumpet_low     (results in error due to duplicate file names) -- same as existing
[p]playsound trumpet            (chooses one of the 4 files at random)  -- new feature
[p]playsound high                  (results in sound file not found) -- same as existing

### CODE REVIEW

**Comment by tmercswims** [comment]
I want to be clear, I like the additions, I think it is a good idea, and your code is solid. I am not rejecting this pull request.

My only issue is that it is unclear when random sounds are being played. And there are certain situations that will arise that may be a bit weird, such as:
If you have these sounds:
```
rooster.mp3
rimshot.mp3
racecar.mp3
```
then doing `[p]playsound r` will play one of those 3 sounds. I realize that this may be wanted, but if one is unaware that the random sound is a thing they may get confused.

I have yet to come up with a way to solve this dilemma, so until I do, I will leave this open. And if you have any ideas, I welcome them!

**Comment by ptoast** [comment]
Sure, I think that is a legitimate issue. I will do some thinking about a clever way to do it. The first two thoughts I had were:

- `await self.bot.say("No matches were found, so I randomly selected a partial match for you.")`
- Add a command, such as `[p]randomsound [on/off]`, to toggle the feature (off by default).

One or both of those could be implemented.

**Comment by tmercswims** [comment]
I think the first would get too spammy. I actually like the toggle idea, because then a user would have to knowingly enable the random choice, so it wouldn't come as a surprise.

**Comment by tmercswims** [comment]
Closing this ;p

**Pull request closed without merging**
