### PR TITLE
added seperate channels for leave and ban event messsages in welcome

### PR DESCRIPTION
**Pull request by brandons209**
### I am submitting a...
```
 [ ] Bug fix
 [X] Feature addition or improvement for an existing cog
```

### Name of the cog in question:
Welcome

### Description of my bug fix/improvement:
Added separate channels for leave and ban/unban messages. Figured not everyone wants all messages to go to a single channel, as in my case.

### CODE REVIEW

**Comment by tmercswims** [comment]
I like where this is going, but I don't think it's quite there yet. To keep things generic, each of the four events should have a `channel` config. If set, an event's message will go to that channel; if not, it will use the cog-level one. (And the cog channel will also be the fallback if the event-specific channel is unavailable for whatever reason.) So there will be a new set of commands, `[p]welcomeset <event> channel <channel>`, and a corresponding config for each, which should default to `None`.

**Comment by brandons209** [comment]
Alright, I agree with that, I'll work that in soon.

**Comment by brandons209** [comment]
Alright, made the changes, wasn't that much needed to be added, since its built pretty well. :)

**Comment by tmercswims** [comment]
I hope you don't mind, but I took the liberty of pulling your fork and fixing all the conflicts that I caused. I also made the channel setter generic, like the others.

Thank you very much for the idea and the contribution! :)

**Comment by brandons209** [comment]
No problem. Down the line I'm going to be adding something that'll keep track of peoples info like roles, times joined server, and such so that when people leave it can post their roles, when they joined, maybe even their last message or something for more information.

**Pull request merged**
