### PR TITLE
Prevent exceptions when handling events

### PR DESCRIPTION
**Pull request by Aioxas**
This PR aims to resolve the following issues:

*Make the file be PEP8-complaint (optional)

*Clean up the code by replacing context with the faster "ctx" (optional)

*Prevent the exceptions occurred while handling events due to self.bot.type() not knowing where to send typing. (Important)

### CODE REVIEW

**Comment by tmercswims** [comment]
Thanks to this pull request, I realize why the cog was just not working: the `type()` thing.

I appreciate your work, I want to merge this, but I must ask that you restore the type hints. I know it's unusual for Python, but I rather like it. If you do that, then I will merge.

**Comment by Aioxas** [comment]
the type hints? Are you referring to self.bot.type?

**Comment by Aioxas** [comment]
If so, I replaced them with self.bot.send_typing, which is almost the same, except you can specify a channel (in this case the welcome channel)

**Comment by tmercswims** [comment]
Sorry, that wasn't clear: I meant the typing of the arguments of functions, like
```
async def _join(self, ctx: discord.context.Context, *, format_str: str):
```
The bits that tell what type the arguments are.

**Comment by Aioxas** [comment]
Oh. uh...okay. I would need to reverse it almost all, but gimme a minute.

**Comment by Aioxas** [comment]
Check it now please.

**Pull request merged**
